# Generated by Django 4.2.27 on 2026-08-02 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_actu', '0002_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at'], 'verbose_name': 'Message de contact', 'verbose_name_plural': 'Messages de contact'},
        ),
        migrations.AlterModelOptions(
            name='favori',
            options={'ordering': ['-created_at'], 'verbose_name': 'Favori', 'verbose_name_plural': 'Favoris'},
        ),
        migrations.AddField(
            model_name='contact',
            name='lu',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='annonce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='gestion_actu.annonce'),
        ),
        migrations.AlterField(
            model_name='favori',
            name='annonce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='gestion_actu.annonce'),
        ),
        migrations.AlterField(
            model_name='favori',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='contact',
            table='contact',
        ),
        migrations.AlterModelTable(
            name='favori',
            table='favori',
        ),
    ]
