# Generated by Django 4.2.27 on 2026-08-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_actu', '0003_alter_contact_options_alter_favori_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresAgence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_agence', models.CharField(default='MyCitiNest', max_length=120)),
                ('telephone', models.CharField(default='+226 65 17 04 60', max_length=30)),
                ('whatsapp', models.CharField(default='+226 65 17 04 60', max_length=30)),
                ('email', models.EmailField(default='contact@mycitinest.com', max_length=254)),
                ('adresse', models.CharField(default='Ouaga 2000, Ouagadougou, Burkina Faso', max_length=255)),
                ('site_web', models.URLField(blank=True, default='https://www.mycitinest.com')),
                ('facebook', models.URLField(blank=True, default='https://facebook.com/mycitinest')),
                ('instagram', models.URLField(blank=True, default='https://instagram.com/mycitinest')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parametres agence',
                'verbose_name_plural': 'Parametres agence',
                'db_table': 'parametres_agence',
            },
        ),
    ]
