# Generated by Codex on 2026-08-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_actu', '0004_parametresagence'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametresagence',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='agence/'),
        ),
    ]
