# Generated by Django 4.2.27 on 2026-08-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_actu', '0005_parametresagence_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametresagence',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='agence/'),
        ),
    ]
