# Generated by Django 4.2.27 on 2026-08-02 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_actu', '0006_parametresagence_logo_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['ordre', 'pk'], 'verbose_name': 'Photo', 'verbose_name_plural': 'Photos'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['ordre', 'pk'], 'verbose_name': 'Vidéo', 'verbose_name_plural': 'Vidéos'},
        ),
    ]
