# Generated by Codex on 2026-08-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_actu', '0007_alter_photo_options_alter_video_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='telephone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
