# Generated by Django 4.2.27 on 2026-08-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_actu', '0008_annonce_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametresagence',
            name='feature1_desc',
            field=models.CharField(default='Zéro arnaque', max_length=200),
        ),
        migrations.AddField(
            model_name='parametresagence',
            name='feature1_title',
            field=models.CharField(default='Site officiel', max_length=100),
        ),
        migrations.AddField(
            model_name='parametresagence',
            name='feature2_desc',
            field=models.CharField(default='Biens contrôlés', max_length=200),
        ),
        migrations.AddField(
            model_name='parametresagence',
            name='feature2_title',
            field=models.CharField(default='Annonces vérifiées', max_length=100),
        ),
        migrations.AddField(
            model_name='parametresagence',
            name='feature3_desc',
            field=models.CharField(default='Conseils personnalisés', max_length=200),
        ),
        migrations.AddField(
            model_name='parametresagence',
            name='feature3_title',
            field=models.CharField(default='Accompagnement', max_length=100),
        ),
        migrations.AddField(
            model_name='parametresagence',
            name='feature4_desc',
            field=models.CharField(default='En toute simplicité', max_length=200),
        ),
        migrations.AddField(
            model_name='parametresagence',
            name='feature4_title',
            field=models.CharField(default='Transactions sécurisées', max_length=100),
        ),
    ]
